name: Build Windows App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # ✅ 建议一起升级
        with:
          submodules: true  # ✅ 拉取子模块（插件）

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build Windows executable
        run: flutter build windows

      - name: Upload artifact
        uses: actions/upload-artifact@v4  # ✅ 改成v4
        with:
          name: Bujuan-Windows
          path: build/windows/runner/Release/
